### ISSUE TITLE
update your youtube_answers.json

### ISSUE THREAD

**Issue by supmyhava** [Doc-SLAV/catsgang#3]
i added the rest of the codes

{
    "youtube_answers": [
      {
        "title": "Earn $1000 Just by Listening To Music!",
        "answer": "BAG"
      },
      {
        "title": "How To Make 10x On Crypto",
        "answer": "ABSTRACT"
      },
      {
        "title": "How To Make 10x On Crypto PART 2",
        "answer": "AUCTION"
      },
      {
        "title": "How To Make 10x On Crypto PART 3",
        "answer": "AUDIT"
      },
      {
        "title": "Futures Trading PART 2",
        "answer": "WEI"
      },
      {
        "title": "Futures Trading PART 1",
        "answer": "AIRNODE"
      },
      {
        "title": "FREE Crypto",
        "answer": "dip"
      },
      {
        "title": "Boost Your Cats Earnings!",
        "answer": "dildo"
      },
      {
        "title": "GET RICH NOW",
        "answer": "BAKERS"
      },
      {
        "title": "Productivity Tips!",
        "answer": "BAKING"
      },
      {
        "title": "Start From ZERO",
        "answer": "ALPHA"
      },
      {
        "title": "How to Stay Productive",
        "answer": "ALTCOIN"
      },
      {
        "title": "Earn $100+ per Day",
        "answer": "BITS"
      },
      {
        "title": "Watching YouTube Videos!",
        "answer": "ASIC"
      },
      {
        "title": "Get Paid TO WATCH!",
        "answer": "BITPAY"
      },
      {
        "title": "Make Money Online For FREE",
        "answer": "BIT"
      },
      {
        "title": "Make Money Online For Free",
        "answer": "AFFILIATE"
      },
      {
        "title": "Easy Crypto Airdrops",
        "answer": "MARKET"
      },
      {
        "title": "Make $100,000 in 6 Months",
        "answer": "MAINNET"
      },
      {
        "title": "Learned to Code!",
        "answer": "LEDGER"
      },
      {
        "title": "Job Without a Degree",
        "answer": "LAMBO"
      },
      {
        "title": "EARN $30 PER WORD",
        "answer": "BLOCK"
      },
      {
        "title": "Start Earning Now!",
        "answer": "BOTS"
      },
      {
        "title": "Top Shocking Ways",
        "answer": "ASSET"
      },
      {
        "title": "Amazon Success!",
        "answer": "OPTION"
      },
      {
        "title": "Get Free Money Now!",
        "answer": "OPTION"
      },
      {
        "title": "FREE Money From Rich People!",
        "answer": "BASKET"
      },
      {
        "title": "Change Your Life!",
        "answer": "BOUNTY"
      },
      {
        "title": "BLOCKCHAIN TIPS",
        "answer": "BRIDGES"
      },
      {
        "title": "Make $5,000+ Per MONTH",
        "answer": "BITCOINER"
      },
      {
        "title": "Pinterest Affiliate Marketing",
        "answer": "BITSTREAM"
      },
      {
        "title": "Earn Real Money Playing Games! ",
        "answer": "BUBBLE"
      }
    ]
  }

**Comment by Doc-SLAV** [comment]
"title": "Earn Real Money Playing Games! ",
"answer": "BUBBLE"

this not working from the server bot
all answer update every release quiz

**Comment by supmyhava** [comment]
> "title": "Earn Real Money Playing Games! ", "answer": "BUBBLE"
> 
> this not working from the server bot all answer update every release quiz

it worked for me
also must have the space in the end...
